---
logging:
  level:
    root: DEBUG
    com.example.metro_parking_web_service: DEBUG
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
external-server:
  carpark:
    base-url: https://your-base-url
    apikey: apikey your-apikey
