---
spring:
  profiles:
    active: local
logging:
  level:
    root: INFO
    com.example.metro_parking_web_service: INFO
    sun.rmi: INFO
    javax.management: INFO
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
external-server:
  parking:
    base-url: https://your-base-url
    api: your-api
    apikey: your-api-key
