---
spring:
  application:
    name: metro-parking-web-service
  kafka:
    bootstrap-servers: localhost:9092
  mongodb:
    host: localhost
    port: 27017
    representation:
      uuid: standard
logging:
  level:
    root: INFO
    com.example.metro_parking_web_service: INFO
service:
  cors:
    allowed-origins: "${CORS_ALLOWED_ORIGINS}"
management:
  endpoints:
    web:
      base-path: "${ACTUATOR_BASE_PATH:/actuator}"
      exposure:
        include: "health, readiness, startup"
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: false
  swagger-ui:
    display-request-duration: true
    path: /swagger-ui.html
    enabled: false
  show-actuator: false
server:
  port: 8080
external-server:
  carpark:
    base-url: "${SERVICE_URL}"
    apikey: "${OPEN_DATA_APIKEY}"
